# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9ed06a767603fdafc02c5f0c0a056f044b74bce5f6d02e4ab435ec1a81900c450c870384938990d36283e487def6b9092dccbdf03a1dd801f251ba7b68aa43

test:
  secret_key_base: 5e68d8c972e6244c6d00b4b9abf8c4b008437fe3a7d06dbf1946626a14d4e114ffd003e4c5c45ff08c17451be5a9eb300b303d17eab979cf20f14e48e6cf5e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
